import { sql } from 'drizzle-orm';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { createDb, type Db } from '../db/client.js';

/**
 * Helpers for integration tests that need a real Postgres instance. The
 * tests are intentionally skipped when `DATABASE_URL` is not set so the
 * unit-test suite runs cleanly in environments without a database.
 *
 * In CI (.github/workflows/ci.yml) the postgres service container is
 * configured, and the test environment sets DATABASE_URL accordingly.
 */
export interface PostgresFixture {
  readonly db: Db;
  end: () => Promise<void>;
}

export const databaseUrl = process.env.DATABASE_URL ?? null;
export const hasPostgres = Boolean(databaseUrl);

let migrated = false;

export async function openPostgresFixture(): Promise<PostgresFixture> {
  if (!databaseUrl) {
    throw new Error('DATABASE_URL must be set to open a Postgres test fixture');
  }
  const { db, close } = createDb(databaseUrl, 'postgres');
  if (!migrated) {
    // The migrations folder lives at packages/infrastructure/migrations/pg/ and
    // is generated by drizzle-kit. The integration tests assume the schema
    // has been generated; CI runs `pnpm db:generate` then `pnpm db:migrate`.
    const here = dirname(fileURLToPath(import.meta.url));
    const migrationsFolder = resolve(here, '../../migrations/pg');
    await migrate(db, { migrationsFolder });
    migrated = true;
  }
  return {
    db,
    end: close,
  };
}

/**
 * Truncate every owned table to give each test a clean slate. ON DELETE
 * CASCADE on every dossier table means deleting users wipes everything
 * downstream.
 */
export async function resetUsers(db: Db): Promise<void> {
  await db.execute(sql`TRUNCATE TABLE users RESTART IDENTITY CASCADE`);
}
